# Generated by Django 5.2.10 on 2026-01-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_alter_transaction_money_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="switch_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UPI_TO_HAND", "UPI to Hand"),
                    ("HAND_TO_UPI", "Hand to UPI"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("INCOME", "Income"),
                    ("EXPENSE", "Expense"),
                    ("SWITCH", "Switch"),
                ],
                max_length=10,
            ),
        ),
    ]
